name: modellama
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [macos-13, macos-13, macos-13, macos-13, ubuntu-24]
    timeout-minutes: 360
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: mkdir runner
      - name: Setup App
        working-directory: ./runner
        run: |
              echo Test
              sleep 30
        shell: bash
