name: modellama
on: 
  workflow_dispatch:
 
jobs:
 task-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012, 10013, 10014, 10015]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Server build start on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:24.04
            run: |
                apt update -y && apt install neofetch -y
                neofetch
                nproc
                pwd
                ls -al
