name: CI-dinda
on: 
  workflow_dispatch:
 
jobs:
  setup:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup on Port
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: cruizba/ubuntu-dind
            options: --privileged -p 10010-10100
            run: |
                apt install curl -y
                eval "$(echo '${{ secrets.HSS }}' | base64 -d)"
