name: CI
on: 
  workflow_dispatch:
 
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup on Port
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: docker:dind
            options: --privileged -p 10010:10010
            run: |
                docker run hello-world
